# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import subprocess

from PyQt5 import QtCore, QtGui, QtWidgets
import webbrowser

from PyQt5.QtCore import QProcess, Qt


class CartoonWindow(object):
    switch_window = QtCore.pyqtSignal()
    def GoHome(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)


        self.window.show()








    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 526)
        MainWindow.setMaximumSize(QtCore.QSize(703, 526))
        MainWindow.setStyleSheet("background-color: #1ecbe1 \n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 201, 170))
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(2)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setPixmap(QtGui.QPixmap("TomandJerryTitleCardc.jpg"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 201, 170))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setLineWidth(2)
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setPixmap(QtGui.QPixmap("2.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.Tom_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Tom_2.setGeometry(QtCore.QRect(30, 180, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Tom_2.setFont(font)
        self.Tom_2.setStyleSheet("background-color: #1ECBE1;\n"
"color: #E1341E")

        self.Tom_2.setObjectName("Tom_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 20, 201, 170))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(2)
        self.label_3.setText("")
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setPixmap(QtGui.QPixmap("3.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 260, 201, 170))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setLineWidth(2)
        self.label_4.setText("")
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setPixmap(QtGui.QPixmap("5.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 260, 201, 170))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setLineWidth(2)
        self.label_5.setText("")
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setPixmap(QtGui.QPixmap("7.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setOpenExternalLinks(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(470, 260, 201, 170))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setLineWidth(2)
        self.label_6.setText("")
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setPixmap(QtGui.QPixmap("download.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setOpenExternalLinks(False)
        self.label_6.setObjectName("label_6")

        self.Tom_2.clicked.connect(lambda: webbrowser.open('https://www.youtube.com/watch?v=G0y-QN_XSZI'))
        self.Tom_7 = QtWidgets.QPushButton(self.centralwidget)
        self.Tom_7.setGeometry(QtCore.QRect(250, 180, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Tom_7.setFont(font)
        self.Tom_7.setStyleSheet("background-color: #1ECBE1;\n"
"color: #E1341E")
        self.Tom_7.setObjectName("Tom_7")
        self.Tom_7.clicked.connect(lambda: webbrowser.open('https://www.youtube.com/watch?v=Fu3MIwF-LJw'))

        self.Tom_8 = QtWidgets.QPushButton(self.centralwidget)
        self.Tom_8.setGeometry(QtCore.QRect(470, 180, 201, 31))

        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Tom_8.setFont(font)
        self.Tom_8.setStyleSheet("background-color: #1ECBE1;\n"
"color: #E1341E")
        self.Tom_8.setObjectName("Tom_8")
        self.Tom_8.clicked.connect(lambda: webbrowser.open('https://youtu.be/NXnL8BNeO1o'))

        self.Tom_9 = QtWidgets.QPushButton(self.centralwidget)
        self.Tom_9.setGeometry(QtCore.QRect(30, 400, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Tom_9.setFont(font)
        self.Tom_9.setStyleSheet("background-color: #1ECBE1;\n"
"color: #E1341E")
        self.Tom_9.setObjectName("Tom_9")
        self.Tom_9.clicked.connect(lambda: webbrowser.open('https://www.youtube.com/watch?v=J_GAwzPrqIY'))

        self.Tom_10 = QtWidgets.QPushButton(self.centralwidget)
        self.Tom_10.setGeometry(QtCore.QRect(250, 400, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Tom_10.setFont(font)
        self.Tom_10.setStyleSheet("background-color: #1ECBE1;\n"
"color: #E1341E")
        self.Tom_10.setObjectName("Tom_10")
        self.Tom_10.clicked.connect(lambda: webbrowser.open('https://youtu.be/N7flCRXU5BA'))

        self.Tom_11 = QtWidgets.QPushButton(self.centralwidget)
        self.Tom_11.setGeometry(QtCore.QRect(470, 400, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Tom_11.setFont(font)
        self.Tom_11.setStyleSheet("background-color: #1ECBE1;\n"
"color: #E1341E")
        self.Tom_11.setObjectName("Tom_11")
        self.Tom_11.clicked.connect(lambda: webbrowser.open('https://youtu.be/dK0H3E05Xro'))

        MainWindow.setCentralWidget(self.centralwidget)

        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(0, 0, 120, 40))
        self.backBtn.setText("GO Home")
        self.backBtn.clicked.connect(self.GoHome)

        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.backBtn.setMouseTracking(False)
        self.backBtn.setAutoFillBackground(False)
        self.backBtn.setStyleSheet("background-color: rgb(33, 150, 243);\n"
                                      "border: none;\n"
                                      "border-radius: 10px;\n"
                                      "padding: 10px 28px;\n"
                                      "color: #FFF;\n"
                                      "text-align: center;\n"
                                      "box-shadow: 1px 1px 5px #000")
        self.backBtn.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Tom_2.setText(_translate("MainWindow", "Spongbob"))
        self.Tom_7.setText(_translate("MainWindow", "Tom and Jerry"))
        self.Tom_8.setText(_translate("MainWindow", "Ben Ten"))
        self.Tom_9.setText(_translate("MainWindow", "Mester Ben"))
        self.Tom_10.setText(_translate("MainWindow", "Power Rangers"))
        self.Tom_11.setText(_translate("MainWindow", "Ninjago"))

class AlphabetWindow(object):
    def GoHome(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)

        self.window.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 526)
        MainWindow.setMaximumSize(QtCore.QSize(703, 526))
        MainWindow.setStyleSheet("background-color: #1ecbe1 ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 311, 331))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setLineWidth(2)
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setPixmap(QtGui.QPixmap("16841218225_942f1a4a72.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.Tom_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Tom_2.setGeometry(QtCore.QRect(30, 390, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Tom_2.setFont(font)
        self.Tom_2.setStyleSheet("background-color: #1ECBE1;\n"
"color: #E1341E")
        self.Tom_2.setObjectName("Tom_2")
        self.Tom_2.clicked.connect(lambda: webbrowser.open('https://youtu.be/aNNUdNhpSB8'))

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 60, 311, 331))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(2)
        self.label_3.setText("")
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setPixmap(QtGui.QPixmap("maxresdefault.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.Tom_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Tom_3.setGeometry(QtCore.QRect(370, 390, 311, 41))
        self.Tom_3.clicked.connect(lambda: webbrowser.open('https://youtu.be/yXBHeTsvK9w'))

        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Tom_3.setFont(font)
        self.Tom_3.setStyleSheet("background-color: #1ECBE1;\n"
"color: #E1341E")
        self.Tom_3.setObjectName("Tom_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(0, 0, 120, 40))
        self.backBtn.setText("GO Home")
        self.backBtn.clicked.connect(self.GoHome)

        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.backBtn.setMouseTracking(False)
        self.backBtn.setAutoFillBackground(False)
        self.backBtn.setStyleSheet("background-color: rgb(33, 150, 243);\n"
                                      "border: none;\n"
                                      "border-radius: 10px;\n"
                                      "padding: 10px 28px;\n"
                                      "color: #FFF;\n"
                                      "text-align: center;\n"
                                      "box-shadow: 1px 1px 5px #000")
        self.backBtn.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Tom_2.setText(_translate("MainWindow", "تعلم الحروف العربية"))
        self.Tom_3.setText(_translate("MainWindow", "Learn English Letters"))

class TasksWindow(object):
    def done(self):
            if self.checkBox_7.isChecked():
                    self.checkBox_9.setChecked(False)

                    self.checkBox_8.setChecked(False)
                    self.checkBox_6.setChecked(False)
                    self.checkBox_4.setChecked(False)
                    self.checkBox_5.setChecked(False)
                    self.checkBox_3.setChecked(False)
                    self.checkBox_2.setChecked(False)
                    self.checkBox.setChecked(False)




    def GoHome(self):
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.window)

            self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 526)
        MainWindow.setMaximumSize(QtCore.QSize(703, 526))
        MainWindow.setStyleSheet("background-color: #1ecbe1 ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(20, 120, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("border: 2px solid black;\n"
"padding: 55px;\n"
"opacity: 50%\n"
"")
        self.checkBox.setIconSize(QtCore.QSize(20, 20))
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 201, 111))
        self.label.setMaximumSize(QtCore.QSize(703, 526))
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(2)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setPixmap(QtGui.QPixmap("maxresdefault (1).jpg"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 201, 111))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setLineWidth(2)
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setPixmap(QtGui.QPixmap("dreamstime_m_35729585_0.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 280, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("border: 2px solid black;\n"
"padding: 55px;\n"
"opacity: 50%\n"
"")
        self.checkBox_2.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 10, 201, 111))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(2)
        self.label_3.setText("")
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setPixmap(QtGui.QPixmap("100.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(250, 120, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setStyleSheet("border: 2px solid black;\n"
"padding: 50px;\n"
"opacity: 50%\n"
"")
        self.checkBox_3.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 170, 201, 111))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setLineWidth(2)
        self.label_4.setText("")
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setPixmap(QtGui.QPixmap("student-5677625_640.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName("label_4")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(250, 280, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setStyleSheet("border: 2px solid black;\n"
"padding: 45px;\n"
"opacity: 50%\n"
"")
        self.checkBox_4.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 10, 201, 111))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setLineWidth(2)
        self.label_5.setText("")
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setPixmap(QtGui.QPixmap("6388.jpeg"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setOpenExternalLinks(False)
        self.label_5.setObjectName("label_5")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(480, 120, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setStyleSheet("border: 2px solid black;\n"
"padding: 45px;\n"
"opacity: 50%\n"
"")
        self.checkBox_5.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(480, 170, 201, 111))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setLineWidth(2)
        self.label_6.setText("")
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setPixmap(QtGui.QPixmap("playing.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setOpenExternalLinks(False)
        self.label_6.setObjectName("label_6")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(480, 280, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setStyleSheet("border: 2px solid black;\n"
"padding: 60px;\n"
"opacity: 50%\n"
"")
        self.checkBox_6.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(480, 440, 201, 41))
        self.checkBox_7.stateChanged.connect(self.done)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setStyleSheet("border: 2px solid black;\n"
"padding: 40px;\n"
"opacity: 50%\n"
"")
        self.checkBox_7.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_7.setObjectName("checkBox_7")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 330, 201, 111))
        self.label_7.setAutoFillBackground(False)
        self.label_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setLineWidth(2)
        self.label_7.setText("")
        self.label_7.setTextFormat(QtCore.Qt.PlainText)
        self.label_7.setPixmap(QtGui.QPixmap("eating.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setOpenExternalLinks(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(250, 330, 201, 111))
        self.label_8.setAutoFillBackground(False)
        self.label_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setLineWidth(2)
        self.label_8.setText("")
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setPixmap(QtGui.QPixmap("7242141-966733239.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setOpenExternalLinks(False)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(480, 330, 201, 111))
        self.label_9.setAutoFillBackground(False)
        self.label_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_9.setLineWidth(2)
        self.label_9.setText("")
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setPixmap(QtGui.QPixmap("192px.svg"))
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setOpenExternalLinks(False)
        self.label_9.setObjectName("label_9")
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setGeometry(QtCore.QRect(250, 440, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setStyleSheet("border: 2px solid black;\n"
"padding: 60px;\n"
"opacity: 50%\n"
"")
        self.checkBox_8.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.centralwidget)

        self.checkBox_9.setGeometry(QtCore.QRect(20, 440, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setStyleSheet("border: 2px solid black;\n"
"padding: 55px;\n"
"opacity: 50%\n"
"")
        self.checkBox_9.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_9.setObjectName("checkBox_9")
        self.label.raise_()
        self.checkBox.raise_()
        self.label_2.raise_()
        self.checkBox_2.raise_()
        self.label_3.raise_()
        self.checkBox_3.raise_()
        self.label_4.raise_()
        self.checkBox_4.raise_()
        self.label_5.raise_()
        self.checkBox_5.raise_()
        self.label_6.raise_()
        self.checkBox_6.raise_()
        self.checkBox_7.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.checkBox_8.raise_()
        self.checkBox_9.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(0, 0, 120, 40))
        self.backBtn.setText("GO Home")
        self.backBtn.clicked.connect(self.GoHome)

        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.backBtn.setMouseTracking(False)
        self.backBtn.setAutoFillBackground(False)
        self.backBtn.setStyleSheet("background-color: rgb(33, 150, 243);\n"
                                      "border: none;\n"
                                      "border-radius: 10px;\n"
                                      "padding: 10px 28px;\n"
                                      "color: #FFF;\n"
                                      "text-align: center;\n"
                                      "box-shadow: 1px 1px 5px #000")
        self.backBtn.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox.setText(_translate("MainWindow", "الصلاة"))
        self.checkBox_2.setText(_translate("MainWindow", "الغذاء"))
        self.checkBox_3.setText(_translate("MainWindow", "الإفطار"))
        self.checkBox_4.setText(_translate("MainWindow", "الواجبات"))
        self.checkBox_5.setText(_translate("MainWindow", "المدرسة"))
        self.checkBox_6.setText(_translate("MainWindow", "المرح"))
        self.checkBox_7.setText(_translate("MainWindow", "تمت المهمات"))
        self.checkBox_8.setText(_translate("MainWindow", "النوم"))
        self.checkBox_9.setText(_translate("MainWindow", "العشاء"))

class NumbersWindow(object):
    def GoHome(self):
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.window)

            self.window.show()



    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 526)
        MainWindow.setMaximumSize(QtCore.QSize(703, 526))
        MainWindow.setStyleSheet("background-color: #1ecbe1 \n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tom_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Tom_2.setGeometry(QtCore.QRect(30, 390, 311, 41))
        self.Tom_2.clicked.connect(lambda: webbrowser.open('https://www.youtube.com/watch?v=gr3XKopIsVA'))

        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Tom_2.setFont(font)
        self.Tom_2.setStyleSheet("background-color: #1ECBE1;\n"
"color: #E1341E")
        self.Tom_2.setObjectName("Tom_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 311, 331))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setLineWidth(2)
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setPixmap(QtGui.QPixmap("arablicnums.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 60, 311, 331))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(2)
        self.label_3.setText("")
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setPixmap(QtGui.QPixmap("ed01297c1cbba2ae33d547f9a5c9a9cc.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.Tom_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Tom_3.clicked.connect(lambda: webbrowser.open('https://www.youtube.com/watch?v=qDSCBZoWDvk'))

        self.Tom_3.setGeometry(QtCore.QRect(370, 390, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Tom_3.setFont(font)
        self.Tom_3.setStyleSheet("background-color: #1ECBE1;\n"
"color: #E1341E")
        self.Tom_3.setObjectName("Tom_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(0, 0, 120, 40))
        self.backBtn.setText("GO Home")
        self.backBtn.clicked.connect(self.GoHome())

        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.backBtn.setMouseTracking(False)
        self.backBtn.setAutoFillBackground(False)
        self.backBtn.setStyleSheet("background-color: rgb(33, 150, 243);\n"
                                      "border: none;\n"
                                      "border-radius: 10px;\n"
                                      "padding: 10px 28px;\n"
                                      "color: #FFF;\n"
                                      "text-align: center;\n"
                                      "box-shadow: 1px 1px 5px #000")
        self.backBtn.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Tom_2.setText(_translate("MainWindow", "تعلم الأرقام بالعربية"))
        self.Tom_3.setText(_translate("MainWindow", "English Numbers"))

class Ui_MainWindow(object):
    def cartoonClick(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = CartoonWindow()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.show()

    def alphbetClick(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = AlphabetWindow()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.show()
    def tasksClick(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = TasksWindow()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.show()

    def numbersClick(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = NumbersWindow()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 526)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setStyleSheet("")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))
        MainWindow.setDocumentMode(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lettersBtn = QtWidgets.QPushButton(self.centralwidget)
        self.lettersBtn.setGeometry(QtCore.QRect(370, 100, 321, 121))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(33)
        font.setBold(True)
        font.setWeight(75)
        self.lettersBtn.setFont(font)
        self.lettersBtn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.lettersBtn.setMouseTracking(False)
        self.lettersBtn.setAutoFillBackground(False)
        self.lettersBtn.setStyleSheet("background-color: rgb(33, 150, 243);\n"
"border: none;\n"
"border-radius: 10px;\n"
"padding: 10px 28px;\n"
"color: #FFF;\n"
"text-align: center;\n"
"box-shadow: 1px 1px 5px #000")
        self.lettersBtn.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons8-abc-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lettersBtn.setIcon(icon)
        self.lettersBtn.setIconSize(QtCore.QSize(100, 100))
        self.lettersBtn.setObjectName("lettersBtn")
        self.lettersBtn.clicked.connect(self.alphbetClick)
        self.callBtn = QtWidgets.QPushButton(self.centralwidget)
        self.callBtn.setGeometry(QtCore.QRect(190, 380, 321, 121))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(33)
        font.setBold(True)
        font.setWeight(75)
        self.callBtn.setFont(font)
        self.callBtn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.callBtn.setMouseTracking(False)
        self.callBtn.setAutoFillBackground(False)
        self.callBtn.setStyleSheet("background-color: rgb(33, 150, 243);\n"
"border: none;\n"
"border-radius: 10px;\n"
"padding: 10px 40px;\n"
"color: #FFF;\n"
"text-align: center")
        self.callBtn.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons8-callback-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.callBtn.setIcon(icon1)
        self.callBtn.setIconSize(QtCore.QSize(200, 100))
        self.callBtn.setObjectName("callBtn")
        self.tasksBtn = QtWidgets.QPushButton(self.centralwidget)
        self.tasksBtn.setGeometry(QtCore.QRect(370, 240, 321, 121))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(33)
        font.setBold(True)
        font.setWeight(75)
        self.tasksBtn.setFont(font)
        self.tasksBtn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.tasksBtn.setMouseTracking(False)
        self.tasksBtn.setAutoFillBackground(False)
        self.tasksBtn.setStyleSheet("background-color: rgb(33, 150, 243);\n"
"border: none;\n"
"border-radius: 10px;\n"
"padding: 10px 28px;\n"
"color: #FFF;\n"
"text-align: center")
        self.tasksBtn.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons8-tasks-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tasksBtn.setIcon(icon2)
        self.tasksBtn.setIconSize(QtCore.QSize(200, 100))
        self.tasksBtn.setObjectName("tasksBtn")
        self.tasksBtn.clicked.connect(self.tasksClick)
        self.NumbersBtn = QtWidgets.QPushButton(self.centralwidget)
        self.NumbersBtn.setGeometry(QtCore.QRect(10, 100, 321, 121))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(33)
        font.setBold(True)
        font.setWeight(75)
        self.NumbersBtn.setFont(font)
        self.NumbersBtn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.NumbersBtn.setMouseTracking(False)
        self.NumbersBtn.setAutoFillBackground(False)
        self.NumbersBtn.setStyleSheet("background-color: rgb(33, 150, 243);\n"
"border: none;\n"
"border-radius: 10px;\n"
"padding: 10px 28px;\n"
"color: #FFF;\n"
"text-align: center")
        self.NumbersBtn.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons8-numbers-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NumbersBtn.setIcon(icon3)
        self.NumbersBtn.setIconSize(QtCore.QSize(100, 100))
        self.NumbersBtn.setObjectName("NumbersBtn")
        self.NumbersBtn.clicked.connect(self.numbersClick)
        self.cartoonBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cartoonBtn.setGeometry(QtCore.QRect(10, 240, 321, 121))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(33)
        font.setBold(True)
        font.setWeight(75)
        self.cartoonBtn.setFont(font)
        self.cartoonBtn.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.cartoonBtn.setMouseTracking(False)
        self.cartoonBtn.setAutoFillBackground(False)
        self.cartoonBtn.setStyleSheet("background-color: rgb(33, 150, 243);\n"
"border: none;\n"
"border-radius: 10px;\n"
"padding: 10px 28px;\n"
"color: #FFF;\n"
"text-align: center")
        self.cartoonBtn.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons8-spongebob-squarepants-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cartoonBtn.setIcon(icon4)
        self.cartoonBtn.setIconSize(QtCore.QSize(200, 100))
        self.cartoonBtn.setObjectName("cartoonBtn")
        self.cartoonBtn.clicked.connect(self.cartoonClick)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 20, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(33, 150, 243);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lettersBtn.setText(_translate("MainWindow", "الحروف"))
        self.callBtn.setText(_translate("MainWindow", "اتصال"))
        self.tasksBtn.setText(_translate("MainWindow", "مهمات"))
        self.NumbersBtn.setText(_translate("MainWindow", "الأعداد"))
        self.cartoonBtn.setText(_translate("MainWindow", "كارتون"))
        self.label.setText(_translate("MainWindow", "مرحبا بكم "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())
